import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CartProvider, { CartContext } from "../context/CartProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "yantun-khaijan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-5 flex justify-between">
          <div>
            <Link href={"/"}>
              <h2 className="text-3xl font-bold">
                Yantun <span className="text-amber-500">Khaijan</span>
              </h2>
            </Link>
          </div>
          <nav className="space-x-2">
            <Link href={"/foods"}>Foods</Link>
            <Link href={"/reviews"}>Reviews</Link>
          </nav>
        </header>
        <main className="p-5">
          <CartProvider>{children}</CartProvider>
        </main>
      </body>
    </html>
  );
}
